### ISSUE TITLE
Cannot use python bindings

### ISSUE THREAD

**Issue by MuadDev** [esemeniuc/openpose-docker#5]
# Problem
If I try to import the python openpose module it cannot be done. Also when I try to search for it in the installed modules I cannot find it.

# Steps to reproduce problem
```bash
# Start the docker
mypc@myuser:~$ docker run -it --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 cwaffles/openpose-python
```
```bash
# Test 1
# Start python3 inside the docker
root@88579176c02b:/openpose# python3
# Try to import openpose, throws error
>>> import openpose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openpose'
```
```bash
# Test 2
# List modules installed inside docker using pip3
pip3 list | grep openpose
# No output
```
```bash
# Test 3
# Start python2 inside the docker
root@88579176c02b:/openpose# python3
# Try to import openpose, throws error
>>> import openpose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openpose'
```
```bash
# Test 4
# Try to run the example from "https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/01_body_from_image.py"
root@88579176c02b:/openpose# cd examples/tutorial_api_python/
root@88579176c02b:/openpose/examples/tutorial_api_python# python3 01_body_from_image.py 
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
Traceback (most recent call last):
  File "01_body_from_image.py", line 26, in <module>
    raise e
  File "01_body_from_image.py", line 23, in <module>
    from openpose import pyopenpose as op
  File "../../python/openpose/__init__.py", line 1, in <module>
    from . import pyopenpose as pyopenpose
ImportError: cannot import name 'pyopenpose'
```

Am I doing something wrong? Do you know of a way to fix this?

**Comment by MuadDev** [comment]
It seems that the python bindings are not really installed, so `pip list` does not work. Furthermore, the relative locations used everywhere inside the `01_body_from_image.py` did not seem to work. To solve this I did the following:
- First I followed the instructions in this post: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1027#issuecomment-455127043 
- Second I replaced all the '../../' prefixed relative paths with absolute paths.
